import mongoose, {
  Schema,
  type Document,
  type Model,
  type Types,
} from "mongoose";

export type BlogStatus =
  | "draft"
  | "published"
  | "scheduled";

export interface IBlogMedia {
  publicId: string;
  secureUrl: string;
  width: number;
  height: number;
  format: string;
  bytes: number;
  resourceType: "image";
  alt: string;
}

export interface IBlog extends Document {
  title: string;
  slug: string;
  excerpt: string;

  /**
   * Sanitized HTML generated by the Tiptap editor.
   */
  content: string;

  coverImage: IBlogMedia | null;

  authorName: string;
  authorRole: string;
  authorImage: IBlogMedia | null;

  category: string;
  tags: string[];

  status: BlogStatus;
  featured: boolean;

  publishedAt: Date | null;

  /**
   * Estimated article reading time in minutes.
   */
  readingTime: number | null;

  scheduledAt: Date | null;

  displayOrder: number;

  seoTitle: string;
  seoDescription: string;
  canonicalUrl: string;

  noIndex: boolean;

  ogTitle: string;
  ogDescription: string;
  ogImage: IBlogMedia | null;

  relatedServices: Types.ObjectId[];
  relatedServiceAreas: Types.ObjectId[];

  createdAt: Date;
  updatedAt: Date;
}

const blogMediaSchema = new Schema<IBlogMedia>(
  {
    publicId: {
      type: String,
      required: true,
      trim: true,
      maxlength: 500,
    },

    secureUrl: {
      type: String,
      required: true,
      trim: true,
      maxlength: 2000,
    },

    width: {
      type: Number,
      required: true,
      min: 1,
    },

    height: {
      type: Number,
      required: true,
      min: 1,
    },

    format: {
      type: String,
      required: true,
      trim: true,
      lowercase: true,
      maxlength: 20,
    },

    bytes: {
      type: Number,
      required: true,
      min: 0,
      max: 100 * 1024 * 1024,
    },

    resourceType: {
      type: String,
      required: true,
      enum: ["image"],
      default: "image",
    },

    alt: {
      type: String,
      default: "",
      trim: true,
      maxlength: 200,
    },
  },
  {
    _id: false,
  },
);

const blogSchema = new Schema<IBlog>(
  {
    title: {
      type: String,
      required: true,
      trim: true,
      minlength: 5,
      maxlength: 160,
    },

    slug: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      lowercase: true,
      minlength: 2,
      maxlength: 180,
      match: /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
    },

    excerpt: {
      type: String,
      required: true,
      trim: true,
      minlength: 20,
      maxlength: 400,
    },

    content: {
      type: String,
      required: true,
      trim: true,
      minlength: 20,
      maxlength: 500000,
    },

    coverImage: {
      type: blogMediaSchema,
      default: null,
    },

    authorName: {
      type: String,
      required: true,
      trim: true,
      minlength: 2,
      maxlength: 100,
    },

    authorRole: {
      type: String,
      default: "",
      trim: true,
      maxlength: 120,
    },

    authorImage: {
      type: blogMediaSchema,
      default: null,
    },

    category: {
      type: String,
      required: true,
      trim: true,
      minlength: 2,
      maxlength: 80,
    },

    tags: {
      type: [String],
      default: [],
      validate: {
        validator: (value: string[]) =>
          value.length <= 20,
        message:
          "A blog post can have a maximum of 20 tags.",
      },
    },

    status: {
      type: String,
      enum: [
        "draft",
        "published",
        "scheduled",
      ],
      default: "draft",
      index: true,
    },

    featured: {
      type: Boolean,
      default: false,
      index: true,
    },

    publishedAt: {
      type: Date,
      default: null,
    },

    readingTime: {
      type: Number,
      default: null,
      min: 1,
      max: 120,
    },

    scheduledAt: {
      type: Date,
      default: null,
    },

    displayOrder: {
      type: Number,
      default: 0,
      min: 0,
      max: 100000,
    },

    seoTitle: {
      type: String,
      default: "",
      trim: true,
      maxlength: 70,
    },

    seoDescription: {
      type: String,
      default: "",
      trim: true,
      maxlength: 170,
    },

    canonicalUrl: {
      type: String,
      default: "",
      trim: true,
      maxlength: 2000,
    },

    noIndex: {
      type: Boolean,
      default: false,
    },

    ogTitle: {
      type: String,
      default: "",
      trim: true,
      maxlength: 120,
    },

    ogDescription: {
      type: String,
      default: "",
      trim: true,
      maxlength: 300,
    },

    ogImage: {
      type: blogMediaSchema,
      default: null,
    },

    relatedServices: [
      {
        type: Schema.Types.ObjectId,
        ref: "Service",
      },
    ],

    relatedServiceAreas: [
      {
        type: Schema.Types.ObjectId,
        ref: "ServiceArea",
      },
    ],
  },
  {
    timestamps: true,
  },
);

/*
 * Main admin listing:
 * status + featured + ordering.
 */
blogSchema.index({
  status: 1,
  featured: 1,
  displayOrder: 1,
});

/*
 * Publication date queries.
 */
blogSchema.index({
  status: 1,
  publishedAt: -1,
});

/*
 * Scheduled posts.
 */
blogSchema.index({
  status: 1,
  scheduledAt: 1,
});

/*
 * Category filtering.
 */
blogSchema.index({
  category: 1,
  status: 1,
});

/*
 * Search support.
 */
blogSchema.index({
  title: "text",
  excerpt: "text",
  slug: "text",
});

/*
 * Related content queries.
 */
blogSchema.index({
  relatedServices: 1,
});

blogSchema.index({
  relatedServiceAreas: 1,
});

const Blog: Model<IBlog> =
  mongoose.models.Blog ||
  mongoose.model<IBlog>("Blog", blogSchema);

export default Blog;